# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created: Thu Mar 19 16:53:24 2015
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Servo_Oculus(object):
    def setupUi(self, Servo_Oculus):
        Servo_Oculus.setObjectName(_fromUtf8("Servo_Oculus"))
        Servo_Oculus.resize(410, 164)
        Servo_Oculus.setMinimumSize(QtCore.QSize(0, 164))
        Servo_Oculus.setMaximumSize(QtCore.QSize(16777215, 164))
        self.verticalLayout_5 = QtGui.QVBoxLayout(Servo_Oculus)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(Servo_Oculus)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.line = QtGui.QFrame(Servo_Oculus)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.ResetButton = QtGui.QPushButton(Servo_Oculus)
        self.ResetButton.setObjectName(_fromUtf8("ResetButton"))
        self.horizontalLayout_5.addWidget(self.ResetButton)
        self.CheckManual = QtGui.QCheckBox(Servo_Oculus)
        self.CheckManual.setChecked(True)
        self.CheckManual.setObjectName(_fromUtf8("CheckManual"))
        self.horizontalLayout_5.addWidget(self.CheckManual)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(Servo_Oculus)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtGui.QLabel(Servo_Oculus)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.PitchSlider = QtGui.QSlider(Servo_Oculus)
        self.PitchSlider.setEnabled(False)
        self.PitchSlider.setMinimum(-33)
        self.PitchSlider.setMaximum(33)
        self.PitchSlider.setOrientation(QtCore.Qt.Horizontal)
        self.PitchSlider.setObjectName(_fromUtf8("PitchSlider"))
        self.horizontalLayout.addWidget(self.PitchSlider)
        self.PitchSpin = QtGui.QSpinBox(Servo_Oculus)
        self.PitchSpin.setEnabled(False)
        self.PitchSpin.setMinimum(-45)
        self.PitchSpin.setMaximum(45)
        self.PitchSpin.setObjectName(_fromUtf8("PitchSpin"))
        self.horizontalLayout.addWidget(self.PitchSpin)
        self.label_4 = QtGui.QLabel(Servo_Oculus)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.YawSlider = QtGui.QSlider(Servo_Oculus)
        self.YawSlider.setEnabled(False)
        self.YawSlider.setMinimum(-45)
        self.YawSlider.setMaximum(45)
        self.YawSlider.setOrientation(QtCore.Qt.Horizontal)
        self.YawSlider.setObjectName(_fromUtf8("YawSlider"))
        self.horizontalLayout_2.addWidget(self.YawSlider)
        self.YawSpin = QtGui.QSpinBox(Servo_Oculus)
        self.YawSpin.setEnabled(False)
        self.YawSpin.setMinimum(-45)
        self.YawSpin.setMaximum(45)
        self.YawSpin.setObjectName(_fromUtf8("YawSpin"))
        self.horizontalLayout_2.addWidget(self.YawSpin)
        self.label_5 = QtGui.QLabel(Servo_Oculus)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)

        self.retranslateUi(Servo_Oculus)
        QtCore.QMetaObject.connectSlotsByName(Servo_Oculus)

    def retranslateUi(self, Servo_Oculus):
        Servo_Oculus.setWindowTitle(QtGui.QApplication.translate("Servo_Oculus", "Servo_Oculus", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Servo_Oculus", "Servo Control", None, QtGui.QApplication.UnicodeUTF8))
        self.ResetButton.setText(QtGui.QApplication.translate("Servo_Oculus", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.CheckManual.setText(QtGui.QApplication.translate("Servo_Oculus", " Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Servo_Oculus", "Pitch", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Servo_Oculus", "Yaw", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Servo_Oculus", "Degrees", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Servo_Oculus", "Degrees", None, QtGui.QApplication.UnicodeUTF8))

